#
# Install Tomcat
#

- name: Add tomcat user group
  group: "name={{ tomcat_system_group }}"

- name: Add tomcat user
  user: "name={{ tomcat_system_user }} group={{ tomcat_system_group }} home={{ tomcat_system_home }} createhome=yes"
  sudo: True

- name: Download Tomcat tarball
  get_url:
    url: "{{ tomcat_download_mirror }}/dist/tomcat/tomcat-{{ tomcat_majorversion }}/v{{ tomcat_majorversion }}.{{ tomcat_minorversion }}.{{ tomcat_patchversion }}/bin/apache-tomcat-{{ tomcat\_majorversion }}.{{ tomcat_minorversion }}.{{ tomcat_patchversion }}.tar.gz"
    dest: "{{ tomcat_download_path }}/apache-tomcat-{{ tomcat_majorversion }}.{{ tomcat_minorversion }}.{{ tomcat_patchversion }}.tar.gz"

- name: Make installation directory for Tomcat
  file:
    path: "{{ tomcat_catalina_home }}"
    state: directory
    mode: "u=rwx,go=rx"

- name: Extract Tomcat archive into installation directory
  unarchive:
    src: "{{ tomcat_download_path }}/apache-tomcat-{{ tomcat_majorversion }}.{{ tomcat_minorversion }}.{{ tomcat_patchversion }}.tar.gz"
    dest: "{{ tomcat_catalina_home }}"
    mode: "u=rwx,go=rx"
    copy: no

- name: Delete Tomcat archive, if requested (default is yes)
  file: path={{ item }} state=absent
  with_items:
    - "{{ tomcat_download_path }}/apache-tomcat-{{ tomcat_majorversion }}.{{ tomcat_minorversion }}.{{ tomcat_patchversion }}.tar.gz"
  ignore_errors: true
  when: tomcat_remove_archive
