#
# Prepare Catalina base directory
#

- name: Create "heapdumps directory
  file:
      path: "{{ tomcat_system_home }}/heapdumps"
      state: directory
      owner: "{{ tomcat_system_user }}"
      group: "{{ tomcat_system_group }}"

- name: Create CATALINA_BASE directory
  file:
      path: "{{ tomcat_catalina_base }}"
      state: directory
      owner: "{{ tomcat_system_user }}"
      group: "{{ tomcat_system_group }}"

- name: Create CATALINA_BASE/bin directory
  file:
      path: "{{ tomcat_catalina_base }}/bin"
      state: directory
      owner: "{{ tomcat_system_user }}"
      group: "{{ tomcat_system_group }}"

- name: Create CATALINA_BASE/conf directory
  file:
      path: "{{ tomcat_catalina_base }}/conf"
      state: directory
      owner: "{{ tomcat_system_user }}"
      group: "{{ tomcat_system_group }}"

- name: Create CATALINA_BASE/logs directory
  file:
      path: "{{ tomcat_catalina_base }}/logs"
      state: directory
      owner: "{{ tomcat_system_user }}"
      group: "{{ tomcat_system_group }}"

- name: Create CATALINA_BASE/shared/lib directory
  file:
      path: "{{ tomcat_catalina_base }}/shared/lib"
      state: directory
      owner: "{{ tomcat_system_user }}"
      group: "{{ tomcat_system_group }}"

- name: Create CATALINA_BASE/temp directory
  file:
      path: "{{ tomcat_catalina_base }}/temp"
      state: directory
      owner: "{{ tomcat_system_user }}"
      group: "{{ tomcat_system_group }}"

- name: Create CATALINA_BASE/webapps directory
  file:
      path: "{{ tomcat_catalina_base }}/webapps"
      state: directory
      owner: "{{ tomcat_system_user }}"
      group: "{{ tomcat_system_group }}"

- name: Create CATALINA_BASE/work directory
  file:
      path: "{{ tomcat_catalina_base }}/work"
      state: directory
      owner: "{{ tomcat_system_user }}"
      group: "{{ tomcat_system_group }}"

- name: Copy "server.xml", using the default recommended settings
  copy:
    src: server.xml
    dest: "{{ tomcat_catalina_base }}/conf/server.xml"

- name: Copy a "web.xml", using the default recommended settings
  copy:
    src: web.xml
    dest: "{{ tomcat_catalina_base }}/conf/web.xml"

- name: Copy "tomcat-users.xml", using the default recommended settings
  copy:
    src: tomcat-users.xml
    dest: "{{ tomcat_catalina_base }}/conf/tomcat-users.xml"
